ckp

diff --git a/bin/build-vagrant b/bin/build-vagrant
--- a/bin/build-vagrant
+++ b/bin/build-vagrant
@@ -5,40 +5,60 @@
 #
 cd $(dirname "$0")
 
+test -d ../vagrant && (cd ../vagrant; vagrant destroy -f) &> /dev/null
+
+base_box=hansode/fedora-21-server-x86_64
+
 # Standard network for us so it always should be vboxnet0
 # Only needed for $BIVIO_GIT_SERVER.
 build_container_net=10.10.10
-. ./build-setup.sh
+. ../libexec/build-setup.sh
 
 box=radiasoft/fedora
-vagrant destroy -f
-vagrant remove "$box"
-rm -f package.box
-rm -f Vagrantfile
+if vagrant box list | grep -s -q "$box"; then
+    # If there is a VM running or dependent on it, will get an error
+    vagrant box remove "$box"
+fi
 
-set -e
 if [[ $BIVIO_GIT_SERVER ]]; then
     # Must be different than install-user.sh (so can run two VMs simultaneously)
     # Shouldn't collide with existing uses (1-60) either. Only important for
     # the build if there is a git server
-    ip=$build_container_net.$(( $(id -u) % 100 + 100 ))
+    declare -i i=$(perl -e 'print(int(rand(50)) + 60)')
+    ip=
+    while (( $i < 255 )); do
+        x=$build_container_net.$i
+        if ! ( echo > /dev/tcp/$x/22 ) >& /dev/null; then
+            ip=$x
+            break
+        fi
+        i+=1
+    done
+    if [[ ! $ip ]]; then
+        echo "Unable to find a free IP address on $build_container_net" 1>&2
+        exit 1
+    fi
     private_net="config.vm.network \"private_network\", ip: \"$ip\""
 fi
+
 cat > Vagrantfile <<EOF
-VAGRANTFILE_API_VERSION = "2"
-Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
-  config.vm.box = "hansode/fedora-21-server-x86_64"
+Vagrant.configure(2) do |config|
+  config.vm.box = "$base_box"
   $private_net
 end
 EOF
 vagrant up
 
 shopt -s nullglob
-# Avoid copying *.box and other unnecessary files
-tar cf - *.{list,py,sh} | vagrant ssh -c "sudo bash -c 'yum install -q -y tar; mkdir /cfg; cd /cfg; tar xf -'"
 
-vagrant ssh -c "sudo bash /cfg/build-linux.sh"
+find *.*[a-z] ! -type d | cpio -o | vagrant ssh -c "sudo bash -c 'mkdir /cfg; cd /cfg; cpio -i'"
+
+# This will update the virtualbox additions if necessary
+bivio_vagrant_ssh 'sudo bash /cfg/build-linux.sh'
 vagrant halt
 vagrant package --output package.box
 vagrant box add "$box" package.box
+# Need to destroy VM because directory is emphemeral
+vagrant destroy -f
+rm -rf Vagrantfile .vagrant.d
 echo 'See README.md to upload'
